name: thedarn
version: stable
version-script: git -C parts/thedarn/build describe --abbrev=0 --tags
summary: Magnificent app which corrects your previous console command.
description: |
  The darn tries to match a rule for the previous command,
  creates a new command using the matched rule and runs it.

grade: stable
confinement: classic

apps:
  thedarn:
    command: bin/thedarn
    environment:
        PYTHONIOENCODING: utf-8
  darn:
    command: bin/darn
    environment:
        PYTHONIOENCODING: utf-8

parts:
  thedarn:
    source: https://github.com/nvbn/thedarn.git
    plugin: python
